use zzupzzup;

INSERT INTO RESTAURANT(MEMBER_ID, OWNER_NAME,
OWNER_IMAGE, RESTAURANT_TEXT, RESTAURANT_NAME, 
RESTAURANT_TEL, STREET_ADDRESS, AREA_ADDRESS, MENU_TYPE)
VALUES('hihi@a.com', '홍진호', 'zzazang.jpg', '짜파게티보다 맛있는집', '거구장',
'010-1234-5678', '서울시 종로구 인사동3길 29', '서울시 종로구 인사동 215-1', '1');

INSERT INTO RESTAURANT(MEMBER_ID, OWNER_NAME,
OWNER_IMAGE, RESTAURANT_TEXT, RESTAURANT_NAME, 
RESTAURANT_TEL, STREET_ADDRESS, AREA_ADDRESS, MENU_TYPE)
VALUES('hihi@a.com', '유희주', 'bab.jpg', '도시락보다 맛있는집', '김가네',
'010-1111-2222', '서울시 종로구 종로 65', '서울시 종로구 종로2가 8-4', '1');

AlTER TABLE RESTAURANT MODIFY COLUMN PARKABLE BOOLEAN;